#!/bin/bash
source /etc/init.d/functions.sh
eerror ""
eerror "Deprecated script. Doesn't work with latest PyQt/sip snapshots"
eerror ""
exit 1
#snapshots date
DATE="${1:-$(date +%F|sed 's/-//g')}" 
# date of qscintilla. Tends to have different snapshot releases than PyQt4/sip
DATEQS="${2:-${DATE}}"

# !! BIG FAT WARNING !!
# SRC_URI on ebuilds point to dev.gentooexperimental.org:/home/hwoarang/public_html/distfiles/
# In case you need to copy the ebuilds on different location please make sure to change SRC_URI as well
# Normally you dont need to override this location if you have account on d.ge.o
TARGET="${3:-"dev.gentooexperimental.org:/home/hwoarang/public_html/distfiles/"}"

# temp directory to save tarballs 
TEMP="/tmp/qting-edge-python-bump/"

OVERLAY="../../" # ugly but hey dont shoot me

# no comments plz :P
if [[ $1 -eq "-h" ]]; then
	echo """
		Example: ./bump-python-snapshots 20090530 20090527
		
		This will bump PyQt4/sip to 20090530 snapshop,
		and qscintilla ebuilds to 20090527 snapshot

	"""
	exit 0
fi

einfo """
	###############################################################################
	# Automatic PyQt4/sip/qtscintilla-{,python}  bump tool for qting-edge overlay #
	# Author: Markos Chandras <hwoarang@gentoo.org>	     		              #
	#									      #
	# Use ./bump-python-snapshots -h for a usage example			      #
	###############################################################################
"""

ebegin "Downloading tarballs..."
wget -P ${TEMP} http://www.riverbankcomputing.co.uk/static/Downloads/sip4/sip-4.8-snapshot-${DATE}.tar.gz || exit
wget -P ${TEMP} http://www.riverbankcomputing.co.uk/static/Downloads/PyQt4/PyQt-x11-gpl-4.5-snapshot-${DATE}.tar.gz || exit
wget -P ${TEMP} http://www.riverbankcomputing.co.uk/static/Downloads/QScintilla2/QScintilla-gpl-2.4-snapshot-${DATEQS}.tar.gz || exit
eend $?

if [[ $? != 0 ]]; then
	eerror "Failed to download tarballs. Exiting..."
	exit $?
fi

# copy the tarballs to mirror
ebegin "Copying files to mirror..."
scp ${TEMP}/PyQt-x11-gpl-4.5-snapshot-${DATE}.tar.gz ${TARGET} || exit
scp ${TEMP}/sip-4.8-snapshot-${DATE}.tar.gz ${TARGET} || exit
scp ${TEMP}/QScintilla-gpl-2.4-snapshot-${DATEQS}.tar.gz ${TARGET} || exit
eend $?

# copy files to local distdir
ebegin "Copying files to distdir..."
cp ${TEMP}/PyQt-x11-gpl-4.5-snapshot-${DATE}.tar.gz $(portageq envvar DISTDIR) || exit
cp ${TEMP}/sip-4.8-snapshot-${DATE}.tar.gz $(portageq envvar DISTDIR) || exit
cp ${TEMP}/QScintilla-gpl-2.4-snapshot-${DATEQS}.tar.gz $(portageq envvar DISTDIR) || exit
eend $?

# bump ebuilds
ebegin "Bumping ebuilds..."

# PyQt4
pushd ${OVERLAY}/dev-python/PyQt4/
tomove=$(find '.' -type f -name "PyQt4-4.5*.ebuild"|tail -1)
einfo "Previous ebuild to use: ${tomove#./}"
mv ${tomove#./} PyQt4-4.5_pre${DATE}.ebuild || exit "Failed to bump PyQt4"
repoman manifest
git add .
echangelog "Automatic snapshot bump, remove old ebuild"
repoman manifest
git add .
popd

# sip
pushd ${OVERLAY}/dev-python/sip/
tomove=$(find '.' -type f -name "sip-4.8_pre2009*.ebuild"|tail -1)
einfo "Previous ebuild to use: ${tomove#./}"
mv ${tomove#./} sip-4.8_pre${DATE}.ebuild || exit "Failed to bump sip"
repoman manifest
git add .
echangelog "Automatic snapshot bump, remove old ebuild"
repoman manifest
git add .
popd

# qscintilla-python
pushd ${OVERLAY}/dev-python/qscintilla-python/
tomove=$(find '.' -type f -name "qscintilla-python-2.4_pre*.ebuild"|tail -1)
einfo "Previous ebuild to use: ${tomove#./}"
mv ${tomove#./} qscintilla-python-2.4_pre${DATEQS}.ebuild || exit "Failed to bump qscintilla-python"
repoman manifest
git add .
echangelog "Automatic snapshot bump, remove old ebuild"
repoman manifest
git add .
popd

# qscintilla
pushd ${OVERLAY}/x11-libs/qscintilla/
tomove=$(find '.' -type f -name "qscintilla-2.4_pre*.ebuild"|tail -1)
einfo "Previous ebuild to use: ${tomove#./}"
mv ${tomove#./} qscintilla-2.4_pre${DATEQS}.ebuild || exit "Failed to bump qscintilla"
repoman manifest
git add .
echangelog "Automatic snapshot bump, remove old ebuild"
repoman manifest
git add .
popd

eend $?

# commit
ebegin "Commiting..."
git commit -a -m "PyQt4/sip/qscintilla{,-python}: Automatic Version bump, remove old" || exit "Failed to commit"
git push || exit "Failed to push"
eend $?

# clean up
ebegin "Cleaning up tarballs..."
rm ${TEMP}/sip-4.8-snapshot-${DATE}.tar.gz || exit
rm ${TEMP}/PyQt-x11-gpl-4.5-snapshot-${DATE}.tar.gz || exit
rm ${TEMP}/QScintilla-gpl-2.4-snapshot-${DATEQS}.tar.gz || exit
rm -r ${TEMP}
eend $?

exit 0
