#!/bin/bash
source /etc/init.d/functions.sh

usage() {
	echo """
Example: ./bump-python-revisions 11cc33 22bba4
	
This will bump PyQt4 ebuild to 11cc33 revision,
and Sip ebuild to snapshot to 22bba4 revision

Use -h option to display this message
Use -c option to skip bumping operation and just 
	directly to merge operation
	"""
}

commit() {
ewarn "Your changes are ready to be merged. However I strongly recommend you to review your changes."
ewarn ""
einfo "Press 'r' to review your changes or 'y' to merge them to master branch (default 'r')."
read choice
case "$choice" in
        y)      ewarn "Your changes will be merged now. Don't break the overlay or I will shoot you down!"
		git commit -a -m "PyQt4/sip: Automatic version bump, remove old" || exit 2
                git push || exit 2
                ;;
	
        r|"")   git diff
                ;;
	*)	eerror ""
		eerror "Invalid option. Are you stupid or something?"
		eerror ""
		exit 3
esac
}


########################## VARIABLES ############################
PREV="${1}" # PyQt4 Revision
SREV="${2}" # Sip Revision
PVER="4.7.3" # PyQt4 current working version
SVER="4.10.2" #$ Sip current working version
PYPKG="PyQt-x11-gpl-${PVER}-snapshot-${PREV}" #Format PyQt4 package
SIPKG="sip-${SVER}-snapshot-${SREV}" # Format Sip package
DATE="$(date +%F|sed 's/-//g')" # date to be added to ebuilds
####################################################################

TARGET="dev.gentooexperimental.org:~/public_html/distfiles/"
TEMP="/tmp/qting-edge-python-bump/"
OVERLAY="../../" # ugly but hey dont shoot me

if [[ -z $1 ]]; then
	eerror " "
	eerror "Invalid usage"
	eerror " "
	usage
	exit 1
elif [[ $1 -eq "-h" ]]; then
	usage
	exit 0
elif [[ $1 -eq "-c" ]];then
	commit
fi

einfo """
	###########################################################
	# Automatic PyQt4/sip bumping tool for qting-edge overlay #
	# Author: Markos Chandras <hwoarang@gentoo.org>	          #
	#						          #
	# Use ./bump-python-revisions -h for a usage example      #
	###########################################################
"""

ebegin "Downloading tarballs..."
wget -P ${TEMP} http://www.riverbankcomputing.co.uk/static/Downloads/sip4/${SIPKG}.tar.gz || exit 2
wget -P ${TEMP} http://www.riverbankcomputing.co.uk/static/Downloads/PyQt4/${PYPKG}.tar.gz || exit 2
eend $?

if [[ $? != 0 ]]; then
	eerror "Failed to download tarballs. Exiting..."
	exit $?
fi

# copy the tarballs to mirror
ebegin "Copying files to mirror..."
scp ${TEMP}/${PYPKG}.tar.gz ${TARGET} || exit
scp ${TEMP}/${SIPKG}.tar.gz ${TARGET} || exit
eend $?

# copy files to local distdir
ebegin "Copying files to distdir..."
cp ${TEMP}/${PYPKG}.tar.gz $(portageq envvar DISTDIR) || exit
cp ${TEMP}/${SIPKG}.tar.gz $(portageq envvar DISTDIR) || exit
eend $?

# bump ebuilds
einfo "Bumping ebuilds..."

# PyQt4
pushd ${OVERLAY}/dev-python/PyQt4/
tomove=$(find '.' -type f -name "PyQt4-${PVER}*.ebuild"|tail -1)
einfo "Previous ebuild to use: ${tomove#./}"
mv ${tomove#./} PyQt4-${PVER}_pre${DATE}.ebuild || exit "Failed to bump PyQt4"
ebegin "Changing revision number to ${PREV}"
sed -i "/^REVISION/s:=.*:${PREV}:" PyQt4-${PVER}_pre${DATE}.ebuild
eend $?
repoman manifest
git add .
popd

# sip
pushd ${OVERLAY}/dev-python/sip/
tomove=$(find '.' -type f -name "sip-${SVER}*.ebuild"|tail -1)
einfo "Previous ebuild to use: ${tomove#./}"
mv ${tomove#./} sip-${SVER}_pre${DATE}.ebuild || exit "Failed to bump sip"
sed -i "/^HG_REVISION/s:=.*:${SREV}:" sip-${SVER}_pre${DATE}.ebuild
eend $?
repoman manifest
git add .
popd

# commit
commit
# clean up
ebegin "Cleaning up tarballs..."
rm ${TEMP}/${SIPKG}.tar.gz || exit
rm ${TEMP}/${PYPKG}.tar.gz || exit
rm -r ${TEMP}
eend $?

exit 0
